### ISSUE TITLE
Differences in cole-kripke results

### ISSUE THREAD

**Issue by kfull17** [dipetkov/actigraph.sleepr#1]
I am trying to apply the actigraph.sleepr package to some agd files to create sleep summary variables for analysis. We have already processed these files previously in Actilife and would like to speed up the process 
we are using by creating an R script using the sleepr package and applying the cole-kripke algorithm. In testing this script we realized the sleep summary results between the actilife processing differ significantly from those we get when we process the same agd file using the cole-kripke algorithm using the R sleepr package. Is the algorithm being used in the same way? Any idea for why our TST times differ so much?

**Comment by dipetkov** [comment]
I will write more tests. For my project I used the Sadeh & Tudor-Locke algorithms, so I've tested those mainly.

The implementations of Cole-Kriple in `actigraph.sleepr` follows this description from ActiGraph:

https://actigraph.desk.com/customer/en/portal/articles/2515585-where-can-i-find-documentation-for-the-sadeh-and-cole-kripke-algorithms-

Is it at all possible to share an example of where the R implementation differs significantly from the ActiLife results?

**Comment by dipetkov** [comment]
This example shows how I've tested the implementation of the Cole-Kripke algorithm in `actigraph.sleepr` against ActiLife 6.13.3.

Let's use some sample data provided by ActiGraph
https://actigraph.desk.com/customer/en/portal/articles/2515507-gt3x-actisleep-sample-data

Note: The samples are .GTX3 files which I have converted into .AGD files using ActiLife since `actigraph.sleepr` can read only .AGD files.

The example data has 10sec epochs. So I reintegrated from 10sec to 60sec epochs and I ran the Cole-Kripke sleep detection algorithm. I save the ActiLife output as `GT3X+ (02 days)10sec60sec-Cole-Kripke.csv`.

You can find both the original 10sec .AGD file and the Cole-Kripke output in this archive: [GT3X+ (02 days).zip](https://github.com/dipetkov/actigraph.sleepr/files/1289710/GT3X.02.days.zip)

And finally the comparison itself:

```

# Using ActiLife 6.13.3
library("actigraph.sleepr")
library("dplyr")
library("lubridate")
library("readr")
library("stringr")
library("testthat")
library("tidyr")

process_sleep_algorithm_output <- function(file) {
  
  algorithm <- 
    readLines(file, 2)          %>% nth(2) %>%
    str_split_fixed(":\\s*", 2) %>% nth(2) %>%
    tolower()
  
  read_csv(file, skip = 3) %>%
    rename_all(tolower) %>%
    unite(timestamp, date, time, sep = " ") %>%
    mutate_at(vars(timestamp), parse_date_time, "%m/%d/%Y %H:%M:S") %>%
    select(timestamp, starts_with("axis"), `sleep or awake?`) %>%
    rename(sleep = `sleep or awake?`) %>%
    mutate(algorithm = !!algorithm)
}

actilife <- 
  process_sleep_algorithm_output("GT3X+ (02 days)10sec60sec-Cole-Kripke.csv")

actisleepr <- 
  read_agd("GT3X+ (02 days)10sec.agd") %>%
  collapse_epochs(60) %>%
  apply_cole_kripke()

expect_identical(actisleepr$sleep, actilife$sleep)
```

I've run this test on more .AGD files but so far I haven't found examples where the Cole-Kripke implementation in actigraph.sleepr doesn't reproduce the ActiLife output.

So it would be great if you can provide such an example.
