### ISSUE TITLE
half_window should be in param ?

### ISSUE THREAD

**Issue by simonprovost** [dipetkov/actigraph.sleepr#5]
**Hello,**

I am currently working with your package R wich again is really useful !! Otherwise, I have a question about apply_sadeh function:

- Could you tell me more about the half_window variable ? It's to take in consideration the new result with the last "n" results ?
- If we change it will we be wrong ?

Thank you for your listening,
Sincerely Yours.

**Comment by dipetkov** [comment]
Hello

I am not sure `half_window` should be a parameter as it is hard-coded in the Sadeh algorithm itself.

Here is the equation given in the paper:
```
PS = 7.601 - 0.065 · Mean-W-5-min - 1.08 · NAT - 0.056 · SD-last 6 min - 0.703·LOG-Act
```
So `half-window` refers to the `5-min` piece in the equation.

Here is a bit more information extracted from Table 1 in the paper:
> Mean-W-5-min is the average number of activity counts during the scored epoch and the window of five epochs preceding and following it; SD-last 6 min is the standard deviation of the activity counts during the scored epoch and the five epochs preceding it; NAT is the number of epochs with activity level equal to or higher than 50 but lower than 100 activity counts in a window of 11 minutes that includes the scored epoch and the five epochs preceding and following it; and LOG-Act is the natural logarithm of the number of activity counts during the scored epoch + 1.

So in short, `Mean-W-5-min` and `NAT` are computed within a 11-epoch window centered at the current epoch while `SD-last 6 min` is computed within a 6-epoch window which ends at the current epoch.

This translates into pseudo-code as:
```
roll(n = 2 * half_window + 1, align = "center")
```
and 
```
roll(n = half_window + 1, align = "right")
```
I just thought it is neater to write it in terms of `half-window` rather than `11` and `6`.
