### ISSUE TITLE
Cole Kripke algorithm does not require specifically 60 second epochs

### ISSUE THREAD

**Issue by aaronjfisher** [dipetkov/actigraph.sleepr#8]
Thank you developing this work!

I wanted to point out an error in citing the Cole Kripke paper. The vignette says that "like the Sadeh algorithm, it [Cole-Kripke] requires 60s epochs and uses a 7-minute window that includes the four previous and two future epochs." This isn't actually true. The 1992 paper developed several different versions of the moving window algorithm for different epoch sizes. In fact, the 1-minute window size performed worse than the other window sizes, at least with their data.

Quoting from page 466:
"The mean-1-minute algorithm always produced accuracy rates below those obtained with the other two algorithms. In the training sample, the percentage of correct sleep/wake identifications produced with the maximum-30-second algorithm exceeded that produced with the 10-second overlapping algorithm, but in the validation sample the 30-second algorithm per- formed more poorly than the 10-second overlapping algorithm. The 10-second nonoverlapping algorithm performed almost as well as the 10-second overlapping algorithm in both the training sample and validation sample."

**Comment by dipetkov** [comment]
You are correct and thank you for pointing out this inaccuracy. I've updated the descriptions as follows:

The original paper proposes three versions of the Cole-Kripke algorithm, optimized for 1-minute, 30-second and 10-second epochs. Here only the 1-min version is implemented and therefore the apply_cole_kripke function requires that the activity data is in 60s epochs. Use the collapse_epochs function to collapse higher-frequency data, if necessary.

The Cole-Kripke algorithm uses the y-axis (axis 1) counts. First epoch counts are divided by 100 and any scaled counts over 300 are clipped to 300. This transformation is specific to ActiGraph devices. The sleep index (SI) is defined as
```
.001 * (106 * epoch_prev(4) + 54 * epoch_prev(3) + 58 * epoch_prev(2) + 76 * epoch_prev(1) +
        230 * epoch + 74 * epoch_next(1) + 67 * epoch_next(2))
```
where at epoch t, epoch_prev(i) is the scaled activity count i epochs before t. Similarly, epoch_next(i) is the scaled activity count i epochs before t. That is, the algorithm uses a 7-epoch window that includes the four preceding and the two subsequent epochs. The time series of activity counts is padded with zeros as necessary, at the beginning and at the end.

Finally, the sleep state is awake (W) if the sleep index SI is less than 1; otherwise the sleep state is asleep (S).
